apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: mysql
      image: 383268345080.dkr.ecr.us-east-1.amazonaws.com/mysql:v2
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "passwors"
